// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManualUser = `-- name: CreateManualUser :one
INSERT INTO users (email, full_name, password_hash) VALUES ($1, $2, $3) RETURNING id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at
`

type CreateManualUserParams struct {
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateManualUser(ctx context.Context, arg CreateManualUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createManualUser, arg.Email, arg.FullName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, description, type, transaction_date, category) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, amount, description, type, transaction_date, category, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID     `json:"user_id"`
	Amount          pgtype.Numeric  `json:"amount"`
	Description     string          `json:"description"`
	Type            TransactionType `json:"type"`
	TransactionDate pgtype.Date     `json:"transaction_date"`
	Category        pgtype.Text     `json:"category"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.Type,
		arg.TransactionDate,
		arg.Category,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Type,
		&i.TransactionDate,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email, full_name, avatar_url) VALUES ($1, $2, $3, $4) RETURNING id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID  pgtype.Text `json:"google_id"`
	Email     string      `json:"email"`
	FullName  string      `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// queries.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT COALESCE(SUM(amount) FILTER (WHERE type = 'INCOME'), 0)::NUMERIC(19, 4) AS total_income, COALESCE(SUM(amount) FILTER (WHERE type = 'EXPENSE'), 0)::NUMERIC(19, 4) AS total_expenses FROM transactions WHERE user_id = $1 AND transaction_date >= $2 AND transaction_date <= $3
`

type GetDashboardSummaryParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetDashboardSummaryRow struct {
	TotalIncome   pgtype.Numeric `json:"total_income"`
	TotalExpenses pgtype.Numeric `json:"total_expenses"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, arg GetDashboardSummaryParams) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpenses)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, amount, description, type, transaction_date, category, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Type,
		&i.TransactionDate,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at FROM users WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUserID = `-- name: ListTransactionsByUserID :many
SELECT id, user_id, amount, description, type, transaction_date, category, created_at, updated_at FROM transactions WHERE user_id = $1 ORDER BY transaction_date DESC, created_at DESC LIMIT $2 OFFSET $3
`

type ListTransactionsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.Type,
			&i.TransactionDate,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET amount = $2, description = $3, type = $4, transaction_date = $5, category = $6 WHERE id = $1 AND user_id = $7 RETURNING id, user_id, amount, description, type, transaction_date, category, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID     `json:"id"`
	Amount          pgtype.Numeric  `json:"amount"`
	Description     string          `json:"description"`
	Type            TransactionType `json:"type"`
	TransactionDate pgtype.Date     `json:"transaction_date"`
	Category        pgtype.Text     `json:"category"`
	UserID          pgtype.UUID     `json:"user_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.Type,
		arg.TransactionDate,
		arg.Category,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.Type,
		&i.TransactionDate,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password_hash = $2 WHERE id = $1 RETURNING id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET full_name = $2, email = $3 WHERE id = $1 RETURNING id, google_id, email, full_name, avatar_url, password_hash, role, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       pgtype.UUID `json:"id"`
	FullName string      `json:"full_name"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
