import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './api';

const toNumber = (value) => {
  if (typeof value === 'number') return value;
  if (typeof value === 'string') return Number(value) || 0;

  if (value && typeof value === 'object') {
    if (typeof value.String === 'string' && value.String !== '') {
      return Number(value.String) || 0;
    }

    if (typeof value.toString === 'function') {
      const parsed = Number(value.toString());
      if (!Number.isNaN(parsed)) return parsed;
    }
  }

  return 0;
};

const toDate = (value) => {
  if (value instanceof Date) return value;

  if (typeof value === 'string' || typeof value === 'number') {
    const parsed = new Date(value);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  if (value && typeof value === 'object') {
    if (typeof value.String === 'string' && value.String !== '') {
      const parsed = new Date(value.String);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    if (
      typeof value.year === 'number' &&
      typeof value.month === 'number' &&
      typeof value.day === 'number'
    ) {
      const parsed = new Date(value.year, value.month - 1, value.day);
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }

    if (typeof value.toString === 'function') {
      const parsed = new Date(value.toString());
      return Number.isNaN(parsed.getTime()) ? null : parsed;
    }
  }

  return null;
};

const formatPdfDate = (value) => {
  const date = toDate(value);
  return date ? formatDate(date) : 'N/A';
};

export const generateTransactionPDF = (transactions, dateRange, userInfo) => {
  const doc = new jsPDF();
  
  // Add header
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text('RupeeFlow - Transaction Statement', 20, 20);
  
  // Add user info and date range
  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(`Account Holder: ${userInfo?.full_name || 'N/A'}`, 20, 35);
  doc.text(`Email: ${userInfo?.email || 'N/A'}`, 20, 45);
  doc.text(`Period: ${dateRange}`, 20, 55);
  doc.text(`Generated: ${formatPdfDate(new Date())}`, 20, 65);
  
  // Add summary
  const totalIncome = transactions
    .filter(t => t.type === 'INCOME')
    .reduce((sum, t) => sum + toNumber(t.amount), 0);
  
  const totalExpense = transactions
    .filter(t => t.type === 'EXPENSE')
    .reduce((sum, t) => sum + toNumber(t.amount), 0);
    
  const netAmount = totalIncome - totalExpense;
  
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text('Summary:', 20, 85);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 128, 0);
  doc.text(`Total Income: ${formatCurrency(totalIncome)}`, 30, 95);
  doc.setTextColor(220, 20, 60);
  doc.text(`Total Expense: ${formatCurrency(totalExpense)}`, 30, 105);
  if (netAmount >= 0) {
    doc.setTextColor(0, 128, 0);
  } else {
    doc.setTextColor(220, 20, 60);
  }
  doc.text(`Net Amount: ${formatCurrency(netAmount)}`, 30, 115);
  
  // Prepare table data
  const tableData = transactions.map(transaction => [
    formatPdfDate(transaction.transaction_date),
    transaction.description,
    transaction.category || 'General',
    transaction.type,
    transaction.type === 'INCOME' 
      ? formatCurrency(toNumber(transaction.amount))
      : `-${formatCurrency(toNumber(transaction.amount))}`
  ]);
  
  // Add transactions table
  autoTable(doc, {
    head: [['Date', 'Description', 'Category', 'Type', 'Amount']],
    body: tableData,
    startY: 130,
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    columnStyles: {
      0: { cellWidth: 25 }, // Date
      1: { cellWidth: 60 }, // Description
      2: { cellWidth: 30 }, // Category
      3: { cellWidth: 25 }, // Type
      4: { cellWidth: 30, halign: 'right' }, // Amount
    },
  });
  
  // Add footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.text(
      `Page ${i} of ${pageCount} | Generated by RupeeFlow`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }
  
  return doc;
};

export const downloadPDF = (transactions, dateRange, userInfo, filename) => {
  const doc = generateTransactionPDF(transactions, dateRange, userInfo);
  doc.save(filename || `RupeeFlow_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
};
